# Generated by Django 4.2 on 2023-04-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_alter_departamento_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='name',
            field=models.CharField(default='default value', max_length=50, verbose_name='Nombre'),
        ),
    ]
