# Generated by Django 4.2 on 2023-05-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_alter_habilidades_options_empleado_hoja_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Apellidos'),
        ),
    ]
